apiVersion: v1
kind: Service
metadata:
  name: bully-headless
spec:
  clusterIP: None
  selector:
    app: bully
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bully
spec:
  serviceName: "bully-headless"
  replicas: 3
  selector:
    matchLabels:
      app: bully
  template:
    metadata:
      labels:
        app: bully
    spec:
      containers:
        - name: bully
          image: bully:latest  
          imagePullPolicy: Never   
          env:
            - name: PROC_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: N_PROCS
              value: "3"
            - name: PEERS
              value: "http://bully-0.bully-headless:8000,http://bully-1.bully-headless:8000,http://bully-2.bully-headless:8000"
          ports:
            - containerPort: 8000

